#### registr profile
POST localhost:8081/auth/registration
Content-Type: application/json

{
  "name": "ali",
  "username": "gg_skins",
  "surname": "aliyev",
  "email": "kontakt20030506@gmail.com",
  "password": "1234"
}

#### login
POST localhost:8081/auth/login
Content-Type: application/json

{
  "username": "gg_skins",
  "password": "1234"
}

#### verify otp
POST localhost:8081/auth/verify-otp/827228
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzQ3MTAwNDUsImVtYWlsIjoia29udGFrdDIwMDMwNTA2QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MzQ3OTY0NDUsImlzcyI6IkxpYnJhcnkifQ.41tR_A3ufZY4FgPjYq2Y9nA9eaP97A3jZKS2jQAq7a1xDlE3zHDyHpgVGiQI2zIC-lXnP30Nmzx9UO77uMyCXQ
