#### registr profile
POST localhost:8081/auth/registration
Content-Type: application/json

{
  "name": "ali",
  "username": "gg_skins",
  "surname": "aliyev",
  "email": "kontakt20030506@gmail.com",
  "password": "1234"
}

#### login
POST localhost:8081/auth/login
Content-Type: application/json

{
  "username": "gg_skins",
  "password": "1234"
}

#### verify otp
POST localhost:8081/auth/verify-otp/987074
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzQ3ODA5NDMsImVtYWlsIjoia29udGFrdDIwMDMwNTA2QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MzQ4NjczNDMsImlzcyI6IkxpYnJhcnkifQ.8CxAoreYXy2IwxWanwl9ipiANmUsQc7ekhtcWJS1ws0PtjgoG_426viLvYBKWFMEUy_cYFIKmT3WbQC5zo1PQw
